### PR TITLE
Added command to set new certificate for OpenVPN Server, updated README

### PR DESCRIPTION
**Pull request by GianlucaUlivi**
As per issue #5

### CODE REVIEW

**Comment by GianlucaUlivi** [comment]
As per issue #5

**Comment by foorschtbar** [comment]
Thanks for the PR! Could you make the openVPN Cert optional via a ENV parameter? Your change enables openVPN even if someone is not using it.

**Comment by GianlucaUlivi** [comment]
> Thanks for the PR! Could you make the openVPN Cert optional via a ENV parameter? Your change enables openVPN even if someone is not using it.

Hi, sure I will check it.
Actually my change should not enable OpenVPN Server, but yes it will set a certificate for it even if not enabled, so pretty useless.
Will check it out and let you know.

**Comment by foorschtbar** [comment]
Thank u!

**Comment by foorschtbar** [comment]
Thank u! closes #5

**Pull request merged**
